# GradCA Optimization Configuration for LUCAS Data
method: "gradca"
enabled: true
description: "Non-robust GradCA on non-linear LUCAS"

data:
  data_path: "data/lucas/lucas_pack.pkl"
  experiment: "lucas"

optimization:
  eta_min: 0.001          # learning rate for T 
  max_iter: 5000
  num_steps_min: 1        # often 1 is fine for non-robust
  tol: 0.0001             #0.00001            
  initialization: "zeros" # good default for GradCA
  gain: 0.0
  optimizers: "adam"

cv:
  k_folds: 5
  seed: 23

output:
  save_directory: "data/lucas/results_nonlinear"
  filename_prefix: "gradca_cv_results_empirical"
